title:             Clean Blog
# email:             your-email@example.com
description:       Deep Reinforcement Learning with Double Q-learning | FlappyBird playground
author:            CS598 Double Q-Learning group
baseurl:           "/"
url:               "http://drl-dql.github.io"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   drl-dql
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
